[build-system]
requires = ["setuptools >= 84.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pipeline-migration-tool"
requires-python = ">=3.12"
authors = [
  {name = "Konflux Build Team"},
]
description = "Pipeline migration tool for Konflux CI."
readme = "README.md"
license = "Apache-2.0"
keywords = ["pipeline", "migration", "konflux", "ci"]
classifiers = [
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Topic :: Software Development :: Build Tools",
]
dynamic = ["version"]

dependencies = [
  "jsonschema==4.26.0",
  "oras==0.2.43",
  "packaging==26.3",
  "requests==2.34.2",
  "ruamel.yaml==0.19.1",
]

[project.optional-dependencies]
test = [
  # Black guarantees stable style in versions released in the same calendar year,
  # but not across years. Pin the major version (which follows the release year).
  # https://black.readthedocs.io/en/stable/the_black_code_style/index.html#stability-policy
  "black~=26.0",
  "flake8",
  "mypy",
  "pytest",
  "pytest-cov",
  "responses",
  "tox",
]

[project.urls]
Homepage = "https://github.com/konflux-ci/pipeline-migration-tool"
Documentation = "https://github.com/konflux-ci/pipeline-migration-tool/blob/main/README.md"
Issues = "https://github.com/konflux-ci/pipeline-migration-tool/issues"

[project.scripts]
pipeline-migration-tool = "pipeline_migration.cli:entry_point"
pmt = "pipeline_migration.cli:entry_point"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
version = {attr = "pipeline_migration.__version__"}

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[tool.coverage.run]
branch = true

[tool.coverage.report]
skip_covered = true
omit = [
  "tests/*"
]
exclude_also = [
    'raise NotImplementedError'
]

[tool.mypy]
ignore_missing_imports = true
namespace_packages = true
explicit_package_bases = true
