apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: pipeline-migration-tool-<VERSION>
  namespace: default-tenant
spec:
  releasePlan: pipeline-migration-tool-releaseplan
  snapshot: <SNAPSHOT_NAME>
  data:
    mapping:
      defaults:
        tags:
          - "<TAG>"
