apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/leitljaroslav/pipeline-migration-tool?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main"
  labels:
    appstudio.openshift.io/application: pipeline-migration-tool-jleitl
    appstudio.openshift.io/component: pipeline-migration-tool-main
    pipelines.appstudio.openshift.io/type: build
  name: pipeline-migration-tool-main-on-push
  namespace: default-tenant